spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-2.c1sy875aigpu.ap-northeast-2.rds.amazonaws.com:3306/innodb
    username: admin
    password: iURm6UHHaHioszpeA9G6
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true