aws:
  access-key: AKIAYKYQWBCPCFVW3T6N
  secret-key: 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
  bucket-name: alarmproject

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: r2dbc:mariadb://125.240.27.115:17001/alarm-project
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG